"""create incidents table

Revision ID: 276f98423ea3
Revises: 1280558553ba
Create Date: 2026-08-28 22:38:26.016863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276f98423ea3'
down_revision: Union[str, Sequence[str], None] = '1280558553ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('guild_id', sa.String(length=100), nullable=True),
    sa.Column('channel_id', sa.String(length=100), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('prediction', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('conversation_excerpt', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_channel_id'), 'incidents', ['channel_id'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_guild_id'), 'incidents', ['guild_id'], unique=False)
    op.create_index(op.f('ix_incidents_reviewed'), 'incidents', ['reviewed'], unique=False)
    op.create_index(op.f('ix_incidents_user_id'), 'incidents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_user_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_reviewed'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_guild_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_channel_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
